name: ShellCheck Lint

# TODO: Include path filters for only .sh files
on:
  push:
  workflow_dispatch:
    

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Find shell scripts
        run: |
          echo "Detecting shell scripts..."
          # list .sh and script files
          # TODO: Ensure all shell files are checked
          find . -type f -name "*.sh" > script_list.txt

      - name: Run ShellCheck
        run: |
          echo "Running ShellCheck on found scripts..."

          # TODO: Currently printing only 'warnings' and 'errors'. Work on refining the scans.
          shellcheck --severity=warning --format=gcc $(cat script_list.txt)